#!/bin/sh

# export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
# alias setupLOCAL='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
# alias setupROOT='localSetupROOT'

source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/atlasLocalSetup.sh

# setupLOCAL 
localSetupROOT 5.34.19-x86_64-slc6-gcc47-opt --skipConfirm

export swdir=`pwd`/../
export LD_LIBRARY_PATH=$swdir/lhapdf/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$swdir/HepMC/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$swdir/fastjet/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$swdir/Pythia8/lib:$LD_LIBRARY_PATH

# export LHAPATH=$swdir/LHApdf/share/LHAPDF/
# export LHAPATH=/afs/cern.ch/sw/lcg/external/MCGenerators/lhapdf/5.8.9/share/lhapdf/PDFsets/
export LHAPATH=$swdir/lhapdf/share/LHAPDF/


export PATH=$swdir/fastjet/bin:$PATH
export PATH=$swdir/lhapdf/bin:$PATH

#export PYTHONPATH=$swdir/genericUtils/python:$PYTHONPATH
